---
apiVersion: v1
kind: Service
metadata:
  name: aiventure
spec:
  type: {{ .Values.service.type }}
  selector:
    app: aiventure
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
